######################################################################
# Automatically generated by qmake (3.0) Mon Dec 5 16:02:32 2016
######################################################################

TEMPLATE = app
TARGET = pomodoro
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
